/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import models.ModelController;
import models.User;

import javax.swing.JFrame;

public class Login extends JFrame {

	public Login() {
		initComponents();
	}

	private User authenticate(String _username, String _password) {
		ModelController controller = new ModelController();
		User user = controller.authenticate(_username, _password);
		return user;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings ("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		txtUsername = new javax.swing.JTextField();
		txtPassword = new javax.swing.JTextField();
		btnLogin = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));
		setLocation(new java.awt.Point(0, 0));
		setName("login"); // NOI18N
		setResizable(false);

		jLabel1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
		jLabel1.setText("Iniciar Sesion");

		txtUsername.setBackground(new java.awt.Color(245, 245, 245));
		txtUsername.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
		txtUsername.setForeground(new java.awt.Color(18, 18, 18));

		txtPassword.setBackground(new java.awt.Color(245, 245, 245));
		txtPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
		txtPassword.setForeground(new java.awt.Color(18, 18, 18));

		btnLogin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
		btnLogin.setText("Ingresar");
		btnLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btnLoginActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout
				.createSequentialGroup()
				.addGap(200, 200, 200)
				.addGroup(layout
					.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
					.addComponent(
						btnLogin,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						220,
						javax.swing.GroupLayout.PREFERRED_SIZE
					)
					.addComponent(
						txtUsername,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						220,
						javax.swing.GroupLayout.PREFERRED_SIZE
					)
					.addComponent(jLabel1)
					.addComponent(
						txtPassword,
						javax.swing.GroupLayout.PREFERRED_SIZE,
						220,
						javax.swing.GroupLayout.PREFERRED_SIZE
					))
				.addGap(200, 200, 200)));
		layout.setVerticalGroup(layout
			.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
			.addGroup(layout
				.createSequentialGroup()
				.addGap(64, 64, 64)
				.addComponent(jLabel1)
				.addGap(48, 48, 48)
				.addComponent(
					txtUsername,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					40,
					javax.swing.GroupLayout.PREFERRED_SIZE
				)
				.addGap(18, 18, 18)
				.addComponent(
					txtPassword,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					40,
					javax.swing.GroupLayout.PREFERRED_SIZE
				)
				.addGap(32, 32, 32)
				.addComponent(
					btnLogin,
					javax.swing.GroupLayout.PREFERRED_SIZE,
					40,
					javax.swing.GroupLayout.PREFERRED_SIZE
				)
				.addGap(64, 64, 64)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {
		String username = txtUsername.getText().toLowerCase().trim();
		String password = txtPassword.getText().toLowerCase().trim();

		System.out.println(username);
		System.out.println(password);

		if (!username.isEmpty() || !password.isEmpty()) {
			User user = authenticate(username, password);
			if (user != null) {
				JFrame dashboard = new Dashboard();
				dashboard.setVisible(true);
				dashboard.setLocationRelativeTo(null);
			} else {
				System.out.println("Error al iniciar sesión");
			}
		}

	}                                        

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btnLogin;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField txtPassword;
	private javax.swing.JTextField txtUsername;
	// End of variables declaration//GEN-END:variables
}
